import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  bg: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  card: {
    width: '88%',
    borderRadius: 32,
    backgroundColor: '#ffffffee',
    padding: 32,
  },
  cardDark: {backgroundColor: '#1a1a1aee'},
  title: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 32,
    color: '#775599',
    textAlign: 'center',
    marginBottom: 20,
  },
  DarkTitle: {
    fontFamily: 'Montserrat-Regular',
    color: '#fff',
    fontSize: 32,
    textAlign: 'center',
    marginBottom: 20,
  },
  subtitle: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 24,
    color: '#775599',
  },
  Darksubtitle: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 24,
    color: '#fff',
  },
  row: {flexDirection: 'row', justifyContent: 'space-between'},
  half: {width: '48%'},
  input: {
    borderWidth: 1,
    borderColor: '#77559950',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    color: '#775599',
  },
  inputDark: {
    borderWidth: 1,
    borderColor: '#555',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    color: '#fff',
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#77559950',
    borderRadius: 16,
    padding: 4,
    paddingLeft: 10,
    marginBottom: 15,
  },
  passwordContainerDark: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#555',
    borderRadius: 16,
    padding: 4,
    paddingLeft: 10,
    marginBottom: 15,
  },
  button: {
    backgroundColor: '#775599',
    borderRadius: 32,
    padding: 16,
    marginTop: 8,
    alignItems: 'center',
  },
  buttonText: {
    fontFamily: 'Montserrat-Regular',
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  link: {
    fontFamily: 'Montserrat-Regular',
    color: '#775599',
    fontWeight: '600',
    marginTop: 14,
  },
  linkDark: {
    fontFamily: 'Montserrat-Regular',
    color: '#fffff7',
    fontWeight: '600',
    marginTop: 14,
  },
  linkAlt: {
    fontFamily: 'Montserrat-Regular',
    color: '#775599aa',
    textAlign: 'center',
    marginTop: 16,
  },
  linkAltDark: {
    fontFamily: 'Montserrat-Regular',
    color: '#c1c1c1',
    textAlign: 'center',
    marginTop: 16,
  },
});

export default styles;
